/* ============================================================
   FAMILY TREE DATA (AUTO-GENERATED)
   ----------------------------------------------------------------
   Generated on: 2026-05-21
   ============================================================ */

window.FAMILY_DATA = {
  "meta": {
    "familyName": "The Sathawane Family Tree",
    "description": "Our family genealogy — maintained with love",
    "version": "1.0.0",
    "createdAt": "2026-05-21",
    "updatedAt": "2026-05-21",
    "rootPersonId": "HITESH_JYOTI_SHANKAR_SATHAWANE",
    "privacy": {
      "hideLivingContactInfo": true,
      "hideLivingDOBYear": false,
      "publicViewAllowed": false
    }
  },
  "persons": [
    {
      "id": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "firstName": "Hitesh",
      "fatherName": "Shankar",
      "motherName": "Jyoti",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1985-12-29",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Engineer",
      "education": "Master in Finantial Management",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "हितेश",
      "lastNameMr": "साठवणे",
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "firstName": "Swati",
      "fatherName": "Bhimrao",
      "motherName": "Chaya",
      "lastName": "Biradar",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1991-07-01",
      "birthPlace": "Latur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Engineer",
      "education": "Master in Finantial Management",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "स्वाती",
      "lastNameMr": "बिरादार",
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "firstName": "Shankar",
      "fatherName": "Sampathrao",
      "motherName": "Vatsala",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1954-08-27",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Retired",
      "education": "MTech Electrical",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "शंकर",
      "lastNameMr": "साठवणे",
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Jyoti",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": "1963-03-23",
      "birthPlace": "Nagpur",
      "deathDate": "2017-05-23",
      "deathPlace": "Dombivli",
      "occupation": "Home Minister",
      "education": "Master of Arts",
      "location": "Dombivli, India",
      "commonName": "Baby",
      "commonNameMr": "बेबी",
      "firstNameMr": "ज्योती",
      "lastNameMr": "वाघमारे",
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "DHRUV_SWATI_HITESH_SATHAWANE",
      "firstName": "Dhruv",
      "fatherName": "Hitesh",
      "motherName": "Swati",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": "2021-11-08",
      "birthPlace": "Dombivli",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": "U KG",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "ध्रुव",
      "lastNameMr": "साठवणे",
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "ARJUN_SWATI_HITESH_SATHAWANE",
      "firstName": "Arjun",
      "fatherName": "Hitesh",
      "motherName": "Swati",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": "2025-12-02",
      "birthPlace": "Dombivli",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SAMPATHRAO___SATHAWANE",
      "firstName": "Sampathrao",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Bhandara",
      "deathDate": "2001-11-26",
      "deathPlace": "Nagpur",
      "occupation": null,
      "education": null,
      "location": "Nagpur, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "firstName": "Mahadeo",
      "fatherName": "Sampathrao",
      "motherName": "Vatsala",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1954-08-27",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Retired",
      "education": "MTech Electrical",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "firstName": "Sudhakar",
      "fatherName": "Sampathrao",
      "motherName": "Vatsala",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1954-08-27",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Retired",
      "education": "MTech Electrical",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "firstName": "Ratnakr",
      "fatherName": "Sampathrao",
      "motherName": "Vatsala",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1954-08-27",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Retired",
      "education": "MTech Electrical",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "firstName": "Alka",
      "fatherName": "Sampathrao",
      "motherName": "Vatsala",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1954-08-27",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Retired",
      "education": "MTech Electrical",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Kalindi",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1963-03-23",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Home Minister",
      "education": "Master of Arts",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Vijay",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1963-03-23",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Home Minister",
      "education": "Master of Arts",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Ajay",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1963-03-23",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Home Minister",
      "education": "Master of Arts",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Shashi",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1963-03-23",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": "Home Minister",
      "education": "Master of Arts",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHIRIKANTH_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Shirikanth",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "deceased",
      "maritalStatus": "single",
      "birthDate": "1963-03-23",
      "birthPlace": "Nagpur",
      "deathDate": "2017-05-23",
      "deathPlace": "Dombivli",
      "occupation": "Home Minister",
      "education": "Master of Arts",
      "location": "Dombivli, India",
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Test living user.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "DHASHRATH___KALEMBE",
      "firstName": "Dhashrath",
      "fatherName": "",
      "motherName": "",
      "lastName": "Kalembe",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "PRAKASH___BISNE",
      "firstName": "Prakash",
      "fatherName": "",
      "motherName": "",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "firstName": "Gaurav",
      "fatherName": "Shankar",
      "motherName": "Jyoti",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1987-09-04",
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "RAJSHREE___LANJEWAR",
      "firstName": "Rajshree",
      "fatherName": "",
      "motherName": "",
      "lastName": "Lanjewar",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1987-09-01",
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "ERISHA_RAJSHREE_GAURAV_SATHAWANE",
      "firstName": "Erisha",
      "fatherName": "Gaurav",
      "motherName": "Rajshree",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": "2024-12-06",
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "firstName": "Rahul",
      "fatherName": "Mahadeo",
      "motherName": "Shaila",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1900-01-19",
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "firstName": "Mrunal",
      "fatherName": "Mahadeo",
      "motherName": "Shaila",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "TAKSHITA_SHRUTI_RAHUL_SATHAWANE",
      "firstName": "Takshita",
      "fatherName": "Rahul",
      "motherName": "Shruti",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SAURABH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "firstName": "Saurabh",
      "fatherName": "Sudhakar",
      "motherName": "Meenakshi",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SIDDHARTH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "firstName": "Siddharth",
      "fatherName": "Sudhakar",
      "motherName": "Meenakshi",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SAMEER_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "firstName": "Sameer",
      "fatherName": "Sudhakar",
      "motherName": "Meenakshi",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "deceased",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "VATSAL_KALPANA_RATNAKR_SATHAWANE",
      "firstName": "Vatsal",
      "fatherName": "Ratnakr",
      "motherName": "Kalpana",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": "1900-09-05",
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHWETAL_ALKA_DHASHRATH_KALEMBE",
      "firstName": "Shwetal",
      "fatherName": "Dhashrath",
      "motherName": "Alka",
      "lastName": "Kalembe",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHIVANI_ALKA_DHASHRATH_KALEMBE",
      "firstName": "Shivani",
      "fatherName": "Dhashrath",
      "motherName": "Alka",
      "lastName": "Kalembe",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "HARSHAL___KHONDE",
      "firstName": "Harshal",
      "fatherName": "",
      "motherName": "",
      "lastName": "Khonde",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "YASHMAK_TRUSHALI_SHWETAL_KALEMBE",
      "firstName": "Yashmak",
      "fatherName": "Shwetal",
      "motherName": "Trushali",
      "lastName": "Kalembe",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "VIRIKA_SHIVANI_HARSHAL_KHONDE",
      "firstName": "Virika",
      "fatherName": "Harshal",
      "motherName": "Shivani",
      "lastName": "Khonde",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "DAKSH_SHIVANI_HARSHAL_KHONDE",
      "firstName": "Daksh",
      "fatherName": "Harshal",
      "motherName": "Shivani",
      "lastName": "Khonde",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "AARTI_KALINDI_PRAKASH_BISNE",
      "firstName": "Aarti",
      "fatherName": "Prakash",
      "motherName": "Kalindi",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1900-05-16",
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "AMIT_KALINDI_PRAKASH_BISNE",
      "firstName": "Amit",
      "fatherName": "Prakash",
      "motherName": "Kalindi",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1900-09-20",
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "VISHAL___PAHUNE",
      "firstName": "Vishal",
      "fatherName": "",
      "motherName": "",
      "lastName": "Pahune",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHRESHT_AARTI_VISHAL_PAHUNE",
      "firstName": "Shresht",
      "fatherName": "Vishal",
      "motherName": "Aarti",
      "lastName": "Pahune",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHRIMEI_AARTI_VISHAL_PAHUNE",
      "firstName": "Shrimei",
      "fatherName": "Vishal",
      "motherName": "Aarti",
      "lastName": "Pahune",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "ANANYA_MAITHALI_AMIT_BISNE",
      "firstName": "Ananya",
      "fatherName": "Amit",
      "motherName": "Maithali",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "VIVAN_MAITHALI_AMIT_BISNE",
      "firstName": "Vivan",
      "fatherName": "Amit",
      "motherName": "Maithali",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SUMEET_HEERA_VIJAY_WAGHMARE",
      "firstName": "Sumeet",
      "fatherName": "Vijay",
      "motherName": "Heera",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SUSMIT_HEERA_VIJAY_WAGHMARE",
      "firstName": "Susmit",
      "fatherName": "Vijay",
      "motherName": "Heera",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "RIYAN_MAYURI_SUSMIT_WAGHMARE",
      "firstName": "Riyan",
      "fatherName": "Susmit",
      "motherName": "Mayuri",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "firstName": "Saurabhi",
      "fatherName": "Ajay",
      "motherName": "Sangeeta",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "firstName": "Aishwarya",
      "fatherName": "Ajay",
      "motherName": "Sangeeta",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "VEDANT_SANGEETA_AJAY_WAGHMARE",
      "firstName": "Vedant",
      "fatherName": "Ajay",
      "motherName": "Sangeeta",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "GAURAV___BHIRUD",
      "firstName": "Gaurav",
      "fatherName": "",
      "motherName": "",
      "lastName": "Bhirud",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHASHWAT___BAVANKAR",
      "firstName": "Shashwat",
      "fatherName": "",
      "motherName": "",
      "lastName": "Bavankar",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "ARYAN_BHAVANA_SHASHI_WAGHMARE",
      "firstName": "Aryan",
      "fatherName": "Shashi",
      "motherName": "Bhavana",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHRIYA_BHAVANA_SHASHI_WAGHMARE",
      "firstName": "Shriya",
      "fatherName": "Shashi",
      "motherName": "Bhavana",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "BHIMRAO___BIRADAR",
      "firstName": "Bhimrao",
      "fatherName": "",
      "motherName": "",
      "lastName": "Biradar",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Father of Swati Biradar.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "CHAYA___BIRADAR",
      "firstName": "Chaya",
      "fatherName": "",
      "motherName": "",
      "lastName": "Biradar",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Swati Biradar.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "VATSALA___SATHAWANE",
      "firstName": "Vatsala",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Shankar Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "BHASKARRAO___WAGHMARE",
      "firstName": "Bhaskarrao",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Father of Jyoti Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "MANAROMA___WAGHMARE",
      "firstName": "Manaroma",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Jyoti Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHAILA___SATHAWANE",
      "firstName": "Shaila",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Rahul Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHRUTI___SATHAWANE",
      "firstName": "Shruti",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Takshita Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "MEENAKSHI___SATHAWANE",
      "firstName": "Meenakshi",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Saurabh Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "KALPANA___SATHAWANE",
      "firstName": "Kalpana",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Vatsal Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "TRUSHALI___KALEMBE",
      "firstName": "Trushali",
      "fatherName": "",
      "motherName": "",
      "lastName": "Kalembe",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Yashmak Kalembe.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "MAITHALI___BISNE",
      "firstName": "Maithali",
      "fatherName": "",
      "motherName": "",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Ananya Bisne.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "HEERA___WAGHMARE",
      "firstName": "Heera",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Sumeet Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "MAYURI___WAGHMARE",
      "firstName": "Mayuri",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Riyan Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SANGEETA___WAGHMARE",
      "firstName": "Sangeeta",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Saurabhi Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "BHAVANA___WAGHMARE",
      "firstName": "Bhavana",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Aryan Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    }
  ],
  "relationships": [
    {
      "id": "R1779358330382_386",
      "type": "marriage",
      "person1Id": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "person2Id": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "startDate": "2015-05-02",
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R1779358330382_982",
      "type": "marriage",
      "person1Id": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "person2Id": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "startDate": "1984-11-29",
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R1779358330382_41",
      "type": "marriage",
      "person1Id": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "person2Id": "DHASHRATH___KALEMBE",
      "startDate": "1984-11-29",
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R1779358330382_88",
      "type": "marriage",
      "person1Id": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "person2Id": "PRAKASH___BISNE",
      "startDate": "1984-11-29",
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R1779358330382_738",
      "type": "marriage",
      "person1Id": "GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "person2Id": "RAJSHREE___LANJEWAR",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R1779358330382_858",
      "type": "marriage",
      "person1Id": "SHIVANI_ALKA_DHASHRATH_KALEMBE",
      "person2Id": "HARSHAL___KHONDE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R1779358330382_862",
      "type": "marriage",
      "person1Id": "AARTI_KALINDI_PRAKASH_BISNE",
      "person2Id": "VISHAL___PAHUNE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R1779358330382_230",
      "type": "marriage",
      "person1Id": "SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "person2Id": "GAURAV___BHIRUD",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R1779358330382_390",
      "type": "marriage",
      "person1Id": "AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "person2Id": "SHASHWAT___BAVANKAR",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R_PC_SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE_HITESH_JYOTI_SHANKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_JYOTI_MANAROMA_BHASKARRAO_WAGHMARE_HITESH_JYOTI_SHANKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SAMPATHRAO___SATHAWANE_SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SAMPATHRAO___SATHAWANE",
      "childId": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HITESH_JYOTI_SHANKAR_SATHAWANE_DHRUV_SWATI_HITESH_SATHAWANE",
      "type": "parent-child",
      "parentId": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "childId": "DHRUV_SWATI_HITESH_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SWATI_CHAYA_BHIMRAO_BIRADAR_DHRUV_SWATI_HITESH_SATHAWANE",
      "type": "parent-child",
      "parentId": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "childId": "DHRUV_SWATI_HITESH_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HITESH_JYOTI_SHANKAR_SATHAWANE_ARJUN_SWATI_HITESH_SATHAWANE",
      "type": "parent-child",
      "parentId": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "childId": "ARJUN_SWATI_HITESH_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SWATI_CHAYA_BHIMRAO_BIRADAR_ARJUN_SWATI_HITESH_SATHAWANE",
      "type": "parent-child",
      "parentId": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "childId": "ARJUN_SWATI_HITESH_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SAMPATHRAO___SATHAWANE_MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SAMPATHRAO___SATHAWANE",
      "childId": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SAMPATHRAO___SATHAWANE_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SAMPATHRAO___SATHAWANE",
      "childId": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SAMPATHRAO___SATHAWANE_RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SAMPATHRAO___SATHAWANE",
      "childId": "RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SAMPATHRAO___SATHAWANE_ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SAMPATHRAO___SATHAWANE",
      "childId": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE_GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_JYOTI_MANAROMA_BHASKARRAO_WAGHMARE_GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_GAURAV_JYOTI_SHANKAR_SATHAWANE_ERISHA_RAJSHREE_GAURAV_SATHAWANE",
      "type": "parent-child",
      "parentId": "GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "childId": "ERISHA_RAJSHREE_GAURAV_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_RAJSHREE___LANJEWAR_ERISHA_RAJSHREE_GAURAV_SATHAWANE",
      "type": "parent-child",
      "parentId": "RAJSHREE___LANJEWAR",
      "childId": "ERISHA_RAJSHREE_GAURAV_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE_RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "type": "parent-child",
      "parentId": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE_MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "type": "parent-child",
      "parentId": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_RAHUL_SHAILA_MAHADEO_SATHAWANE_TAKSHITA_SHRUTI_RAHUL_SATHAWANE",
      "type": "parent-child",
      "parentId": "RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "childId": "TAKSHITA_SHRUTI_RAHUL_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE_SAURABH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "SAURABH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE_SIDDHARTH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "SIDDHARTH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE_SAMEER_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "SAMEER_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE_VATSAL_KALPANA_RATNAKR_SATHAWANE",
      "type": "parent-child",
      "parentId": "RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "VATSAL_KALPANA_RATNAKR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_DHASHRATH___KALEMBE_SHWETAL_ALKA_DHASHRATH_KALEMBE",
      "type": "parent-child",
      "parentId": "DHASHRATH___KALEMBE",
      "childId": "SHWETAL_ALKA_DHASHRATH_KALEMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_ALKA_VATSALA_SAMPATHRAO_SATHAWANE_SHWETAL_ALKA_DHASHRATH_KALEMBE",
      "type": "parent-child",
      "parentId": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "SHWETAL_ALKA_DHASHRATH_KALEMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_DHASHRATH___KALEMBE_SHIVANI_ALKA_DHASHRATH_KALEMBE",
      "type": "parent-child",
      "parentId": "DHASHRATH___KALEMBE",
      "childId": "SHIVANI_ALKA_DHASHRATH_KALEMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_ALKA_VATSALA_SAMPATHRAO_SATHAWANE_SHIVANI_ALKA_DHASHRATH_KALEMBE",
      "type": "parent-child",
      "parentId": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "SHIVANI_ALKA_DHASHRATH_KALEMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHWETAL_ALKA_DHASHRATH_KALEMBE_YASHMAK_TRUSHALI_SHWETAL_KALEMBE",
      "type": "parent-child",
      "parentId": "SHWETAL_ALKA_DHASHRATH_KALEMBE",
      "childId": "YASHMAK_TRUSHALI_SHWETAL_KALEMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HARSHAL___KHONDE_VIRIKA_SHIVANI_HARSHAL_KHONDE",
      "type": "parent-child",
      "parentId": "HARSHAL___KHONDE",
      "childId": "VIRIKA_SHIVANI_HARSHAL_KHONDE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHIVANI_ALKA_DHASHRATH_KALEMBE_VIRIKA_SHIVANI_HARSHAL_KHONDE",
      "type": "parent-child",
      "parentId": "SHIVANI_ALKA_DHASHRATH_KALEMBE",
      "childId": "VIRIKA_SHIVANI_HARSHAL_KHONDE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HARSHAL___KHONDE_DAKSH_SHIVANI_HARSHAL_KHONDE",
      "type": "parent-child",
      "parentId": "HARSHAL___KHONDE",
      "childId": "DAKSH_SHIVANI_HARSHAL_KHONDE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHIVANI_ALKA_DHASHRATH_KALEMBE_DAKSH_SHIVANI_HARSHAL_KHONDE",
      "type": "parent-child",
      "parentId": "SHIVANI_ALKA_DHASHRATH_KALEMBE",
      "childId": "DAKSH_SHIVANI_HARSHAL_KHONDE",
      "relation": "biological"
    },
    {
      "id": "R_PC_PRAKASH___BISNE_AARTI_KALINDI_PRAKASH_BISNE",
      "type": "parent-child",
      "parentId": "PRAKASH___BISNE",
      "childId": "AARTI_KALINDI_PRAKASH_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_KALINDI_MANAROMA_BHASKARRAO_WAGHMARE_AARTI_KALINDI_PRAKASH_BISNE",
      "type": "parent-child",
      "parentId": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "AARTI_KALINDI_PRAKASH_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_PRAKASH___BISNE_AMIT_KALINDI_PRAKASH_BISNE",
      "type": "parent-child",
      "parentId": "PRAKASH___BISNE",
      "childId": "AMIT_KALINDI_PRAKASH_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_KALINDI_MANAROMA_BHASKARRAO_WAGHMARE_AMIT_KALINDI_PRAKASH_BISNE",
      "type": "parent-child",
      "parentId": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "AMIT_KALINDI_PRAKASH_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VISHAL___PAHUNE_SHRESHT_AARTI_VISHAL_PAHUNE",
      "type": "parent-child",
      "parentId": "VISHAL___PAHUNE",
      "childId": "SHRESHT_AARTI_VISHAL_PAHUNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AARTI_KALINDI_PRAKASH_BISNE_SHRESHT_AARTI_VISHAL_PAHUNE",
      "type": "parent-child",
      "parentId": "AARTI_KALINDI_PRAKASH_BISNE",
      "childId": "SHRESHT_AARTI_VISHAL_PAHUNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VISHAL___PAHUNE_SHRIMEI_AARTI_VISHAL_PAHUNE",
      "type": "parent-child",
      "parentId": "VISHAL___PAHUNE",
      "childId": "SHRIMEI_AARTI_VISHAL_PAHUNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AARTI_KALINDI_PRAKASH_BISNE_SHRIMEI_AARTI_VISHAL_PAHUNE",
      "type": "parent-child",
      "parentId": "AARTI_KALINDI_PRAKASH_BISNE",
      "childId": "SHRIMEI_AARTI_VISHAL_PAHUNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AMIT_KALINDI_PRAKASH_BISNE_ANANYA_MAITHALI_AMIT_BISNE",
      "type": "parent-child",
      "parentId": "AMIT_KALINDI_PRAKASH_BISNE",
      "childId": "ANANYA_MAITHALI_AMIT_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AMIT_KALINDI_PRAKASH_BISNE_VIVAN_MAITHALI_AMIT_BISNE",
      "type": "parent-child",
      "parentId": "AMIT_KALINDI_PRAKASH_BISNE",
      "childId": "VIVAN_MAITHALI_AMIT_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VIJAY_MANAROMA_BHASKARRAO_WAGHMARE_SUMEET_HEERA_VIJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "SUMEET_HEERA_VIJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VIJAY_MANAROMA_BHASKARRAO_WAGHMARE_SUSMIT_HEERA_VIJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "SUSMIT_HEERA_VIJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SUSMIT_HEERA_VIJAY_WAGHMARE_RIYAN_MAYURI_SUSMIT_WAGHMARE",
      "type": "parent-child",
      "parentId": "SUSMIT_HEERA_VIJAY_WAGHMARE",
      "childId": "RIYAN_MAYURI_SUSMIT_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AJAY_MANAROMA_BHASKARRAO_WAGHMARE_SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AJAY_MANAROMA_BHASKARRAO_WAGHMARE_AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AJAY_MANAROMA_BHASKARRAO_WAGHMARE_VEDANT_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "VEDANT_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHASHI_MANAROMA_BHASKARRAO_WAGHMARE_ARYAN_BHAVANA_SHASHI_WAGHMARE",
      "type": "parent-child",
      "parentId": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "ARYAN_BHAVANA_SHASHI_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHASHI_MANAROMA_BHASKARRAO_WAGHMARE_SHRIYA_BHAVANA_SHASHI_WAGHMARE",
      "type": "parent-child",
      "parentId": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "SHRIYA_BHAVANA_SHASHI_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R1779360171103_83",
      "type": "marriage",
      "person1Id": "BHIMRAO___BIRADAR",
      "person2Id": "CHAYA___BIRADAR",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_10",
      "type": "marriage",
      "person1Id": "SAMPATHRAO___SATHAWANE",
      "person2Id": "VATSALA___SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_535",
      "type": "marriage",
      "person1Id": "BHASKARRAO___WAGHMARE",
      "person2Id": "MANAROMA___WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_33",
      "type": "marriage",
      "person1Id": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "person2Id": "SHAILA___SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_85",
      "type": "marriage",
      "person1Id": "RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "person2Id": "SHRUTI___SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_224",
      "type": "marriage",
      "person1Id": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "person2Id": "MEENAKSHI___SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_32",
      "type": "marriage",
      "person1Id": "RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "person2Id": "KALPANA___SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_529",
      "type": "marriage",
      "person1Id": "SHWETAL_ALKA_DHASHRATH_KALEMBE",
      "person2Id": "TRUSHALI___KALEMBE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_482",
      "type": "marriage",
      "person1Id": "AMIT_KALINDI_PRAKASH_BISNE",
      "person2Id": "MAITHALI___BISNE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_206",
      "type": "marriage",
      "person1Id": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "person2Id": "HEERA___WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_654",
      "type": "marriage",
      "person1Id": "SUSMIT_HEERA_VIJAY_WAGHMARE",
      "person2Id": "MAYURI___WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_215",
      "type": "marriage",
      "person1Id": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "person2Id": "SANGEETA___WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R1779360171103_600",
      "type": "marriage",
      "person1Id": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "person2Id": "BHAVANA___WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_PC_BHIMRAO___BIRADAR_SWATI_CHAYA_BHIMRAO_BIRADAR",
      "type": "parent-child",
      "parentId": "BHIMRAO___BIRADAR",
      "childId": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "relation": "biological"
    },
    {
      "id": "R_PC_CHAYA___BIRADAR_SWATI_CHAYA_BHIMRAO_BIRADAR",
      "type": "parent-child",
      "parentId": "CHAYA___BIRADAR",
      "childId": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "relation": "biological"
    },
    {
      "id": "R_PC_VATSALA___SATHAWANE_SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "VATSALA___SATHAWANE",
      "childId": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VATSALA___SATHAWANE_MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "VATSALA___SATHAWANE",
      "childId": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VATSALA___SATHAWANE_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "VATSALA___SATHAWANE",
      "childId": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VATSALA___SATHAWANE_RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "VATSALA___SATHAWANE",
      "childId": "RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VATSALA___SATHAWANE_ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "VATSALA___SATHAWANE",
      "childId": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_SHIRIKANTH_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "SHIRIKANTH_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_SHIRIKANTH_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "SHIRIKANTH_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHAILA___SATHAWANE_RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SHAILA___SATHAWANE",
      "childId": "RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHAILA___SATHAWANE_MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SHAILA___SATHAWANE",
      "childId": "MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHRUTI___SATHAWANE_TAKSHITA_SHRUTI_RAHUL_SATHAWANE",
      "type": "parent-child",
      "parentId": "SHRUTI___SATHAWANE",
      "childId": "TAKSHITA_SHRUTI_RAHUL_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MEENAKSHI___SATHAWANE_SAURABH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "MEENAKSHI___SATHAWANE",
      "childId": "SAURABH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MEENAKSHI___SATHAWANE_SIDDHARTH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "MEENAKSHI___SATHAWANE",
      "childId": "SIDDHARTH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MEENAKSHI___SATHAWANE_SAMEER_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "MEENAKSHI___SATHAWANE",
      "childId": "SAMEER_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_KALPANA___SATHAWANE_VATSAL_KALPANA_RATNAKR_SATHAWANE",
      "type": "parent-child",
      "parentId": "KALPANA___SATHAWANE",
      "childId": "VATSAL_KALPANA_RATNAKR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_TRUSHALI___KALEMBE_YASHMAK_TRUSHALI_SHWETAL_KALEMBE",
      "type": "parent-child",
      "parentId": "TRUSHALI___KALEMBE",
      "childId": "YASHMAK_TRUSHALI_SHWETAL_KALEMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MAITHALI___BISNE_ANANYA_MAITHALI_AMIT_BISNE",
      "type": "parent-child",
      "parentId": "MAITHALI___BISNE",
      "childId": "ANANYA_MAITHALI_AMIT_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MAITHALI___BISNE_VIVAN_MAITHALI_AMIT_BISNE",
      "type": "parent-child",
      "parentId": "MAITHALI___BISNE",
      "childId": "VIVAN_MAITHALI_AMIT_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HEERA___WAGHMARE_SUMEET_HEERA_VIJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "HEERA___WAGHMARE",
      "childId": "SUMEET_HEERA_VIJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HEERA___WAGHMARE_SUSMIT_HEERA_VIJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "HEERA___WAGHMARE",
      "childId": "SUSMIT_HEERA_VIJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MAYURI___WAGHMARE_RIYAN_MAYURI_SUSMIT_WAGHMARE",
      "type": "parent-child",
      "parentId": "MAYURI___WAGHMARE",
      "childId": "RIYAN_MAYURI_SUSMIT_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SANGEETA___WAGHMARE_SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "SANGEETA___WAGHMARE",
      "childId": "SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SANGEETA___WAGHMARE_AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "SANGEETA___WAGHMARE",
      "childId": "AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SANGEETA___WAGHMARE_VEDANT_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "SANGEETA___WAGHMARE",
      "childId": "VEDANT_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHAVANA___WAGHMARE_ARYAN_BHAVANA_SHASHI_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHAVANA___WAGHMARE",
      "childId": "ARYAN_BHAVANA_SHASHI_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHAVANA___WAGHMARE_SHRIYA_BHAVANA_SHASHI_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHAVANA___WAGHMARE",
      "childId": "SHRIYA_BHAVANA_SHASHI_WAGHMARE",
      "relation": "biological"
    }
  ],
  "events": [],
  "media": []
};
