/* ============================================================
   FAMILY TREE DATA (AUTO-GENERATED)
   ----------------------------------------------------------------
   Generated on: 2026-08-29
   ============================================================ */

window.FAMILY_DATA = {
  "meta": {
    "familyName": "Sathawane's Family Tree",
    "description": "A genealogy record of the Sathawane family.",
    "version": "1.0.0",
    "createdAt": "2026-08-29",
    "updatedAt": "2026-08-29",
    "rootPersonId": "HITESH_JYOTI_SHANKAR_SATHAWANE",
    "privacy": {
      "hideLivingContactInfo": true,
      "hideLivingDOBYear": false,
      "publicViewAllowed": false
    }
  },
  "persons": [
    {
      "id": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "firstName": "Swati",
      "fatherName": "Bhimrao",
      "motherName": "Chaya",
      "lastName": "Biradar",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1991-07-01",
      "birthPlace": "Latur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "स्वाती",
      "lastNameMr": "बिरादार",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_swati_chaya_bhimrao_biradar.jpg",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_swati_chaya_bhimrao_biradar.jpg",
      "tags": [],
      "private": false
    },
    {
      "id": "SAMPATHRAO___SATHAWANE",
      "firstName": "Sampathrao",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Bhandara",
      "deathDate": "2001-11-26",
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "संपतराव",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_sampathrao___sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_sampathrao___sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "firstName": "Shankar",
      "fatherName": "Sampathrao",
      "motherName": "Vatsala",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1954-08-27",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "शंकर",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_shankar_vatsala_sampathrao_sathawane.jpg",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_shankar_vatsala_sampathrao_sathawane.jpg",
      "tags": [],
      "private": false
    },
    {
      "id": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Jyoti",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": "1963-03-23",
      "birthPlace": "Nagpur",
      "deathDate": "2017-05-23",
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": "Baby",
      "commonNameMr": null,
      "firstNameMr": "ज्योती",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_jyoti_manaroma_bhaskarrao_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_jyoti_manaroma_bhaskarrao_waghmare.jpg",
      "tags": [],
      "private": false
    },
    {
      "id": "DHRUV_SWATI_HITESH_SATHAWANE",
      "firstName": "Dhruv",
      "fatherName": "Hitesh",
      "motherName": "Swati",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": "2021-11-08",
      "birthPlace": "Dombivli",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "ध्रुव",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_dhruv_swati_hitesh_sathawane.jpg",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_dhruv_swati_hitesh_sathawane.jpg",
      "tags": [],
      "private": false
    },
    {
      "id": "ARJUN_SWATI_HITESH_SATHAWANE",
      "firstName": "Arjun",
      "fatherName": "Hitesh",
      "motherName": "Swati",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": "2025-12-02",
      "birthPlace": "Dombivli",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "अर्जुन",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_arjun_swati_hitesh_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_arjun_swati_hitesh_sathawane.jpg",
      "tags": [],
      "private": false
    },
    {
      "id": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "firstName": "Mahadeo",
      "fatherName": "Sampathrao",
      "motherName": "Vatsala",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "महादेव",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_mahadeo_vatsala_sampathrao_sathawane.jpg",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_mahadeo_vatsala_sampathrao_sathawane.jpg",
      "tags": [],
      "private": false
    },
    {
      "id": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "firstName": "Sudhakar",
      "fatherName": "Sampathrao",
      "motherName": "Vatsala",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "सुधाकर",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_sudhakar_vatsala_sampathrao_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_sudhakar_vatsala_sampathrao_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "firstName": "Ratnakr",
      "fatherName": "Sampathrao",
      "motherName": "Vatsala",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "रत्नाकर",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_ratnakr_vatsala_sampathrao_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_ratnakr_vatsala_sampathrao_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "firstName": "Alka",
      "fatherName": "Sampathrao",
      "motherName": "Vatsala",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "अलका",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_alka_vatsala_sampathrao_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_alka_vatsala_sampathrao_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Kalindi",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "कालिंदी",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_kalindi_manaroma_bhaskarrao_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_kalindi_manaroma_bhaskarrao_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Vijay",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "विजय",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_vijay_manaroma_bhaskarrao_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_vijay_manaroma_bhaskarrao_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Ajay",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "अजय",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_ajay_manaroma_bhaskarrao_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_ajay_manaroma_bhaskarrao_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Shashi",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "शशी",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_shashi_manaroma_bhaskarrao_waghmare.jpg",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_shashi_manaroma_bhaskarrao_waghmare.jpg",
      "tags": [],
      "private": false
    },
    {
      "id": "SHIRIKANTH_MANAROMA_BHASKARRAO_WAGHMARE",
      "firstName": "Shirikanth",
      "fatherName": "Bhaskarrao",
      "motherName": "Manaroma",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "deceased",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "श्रीकांत",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_shirikanth_manaroma_bhaskarrao_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_shirikanth_manaroma_bhaskarrao_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "DHASHRATH___KALAMBE",
      "firstName": "Dhashrath",
      "fatherName": "",
      "motherName": "",
      "lastName": "Kalambe",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "दशरथ",
      "lastNameMr": "कळंबे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_dhashrath___kalambe.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_dhashrath___kalambe.png",
      "tags": [],
      "private": false
    },
    {
      "id": "PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE",
      "firstName": "Prakashchandra",
      "fatherName": "Vitthalrao",
      "motherName": "Indirabai",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1947-06-14",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "प्रकाश",
      "lastNameMr": "बिस्ने",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_prakashchandra_indirabai_vitthalrao_bisne.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_prakashchandra_indirabai_vitthalrao_bisne.png",
      "tags": [],
      "private": false
    },
    {
      "id": "GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "firstName": "Gaurav",
      "fatherName": "Shankar",
      "motherName": "Jyoti",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1987-04-09",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "गौरव",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_gaurav_jyoti_shankar_sathawane.jpg",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_gaurav_jyoti_shankar_sathawane.jpg",
      "tags": [],
      "private": false
    },
    {
      "id": "RAJSHREE___LANJEWAR",
      "firstName": "Rajshree",
      "fatherName": "",
      "motherName": "",
      "lastName": "Lanjewar",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1987-01-09",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "राजश्री",
      "lastNameMr": null,
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_rajshree___lanjewar.jpg",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_rajshree___lanjewar.jpg",
      "tags": [],
      "private": false
    },
    {
      "id": "ERISHA_RAJSHREE_GAURAV_SATHAWANE",
      "firstName": "Erisha",
      "fatherName": "Gaurav",
      "motherName": "Rajshree",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": "2024-06-12",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "एरिशा",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_erisha_rajshree_gaurav_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_erisha_rajshree_gaurav_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "firstName": "Rahul",
      "fatherName": "Mahadeo",
      "motherName": "Shaila",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "राहुल",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_rahul_shaila_mahadeo_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_rahul_shaila_mahadeo_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "firstName": "Mrunal",
      "fatherName": "Mahadeo",
      "motherName": "Shaila",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "मृणाल",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_mrunal_shaila_mahadeo_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_mrunal_shaila_mahadeo_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "TAKSHITA_SHRUTI_RAHUL_SATHAWANE",
      "firstName": "Takshita",
      "fatherName": "Rahul",
      "motherName": "Shruti",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "तक्षिता",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_takshita_shruti_rahul_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_takshita_shruti_rahul_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SAURABH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "firstName": "Saurabh",
      "fatherName": "Sudhakar",
      "motherName": "Meenakshi",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "सौरभ",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_saurabh_meenakshi_sudhakar_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_saurabh_meenakshi_sudhakar_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SIDDHARTH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "firstName": "Siddharth",
      "fatherName": "Sudhakar",
      "motherName": "Meenakshi",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "सिद्धार्थ",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_siddharth_meenakshi_sudhakar_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_siddharth_meenakshi_sudhakar_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SAMEER_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "firstName": "Sameer",
      "fatherName": "Sudhakar",
      "motherName": "Meenakshi",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "deceased",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "समीर",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_sameer_meenakshi_sudhakar_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_sameer_meenakshi_sudhakar_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "VATSAL_KALPANA_RATNAKR_SATHAWANE",
      "firstName": "Vatsal",
      "fatherName": "Ratnakr",
      "motherName": "Kalpana",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "वत्सल",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_vatsal_kalpana_ratnakr_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_vatsal_kalpana_ratnakr_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SHWETAL_ALKA_DHASHRATH_KALAMBE",
      "firstName": "Shwetal",
      "fatherName": "Dhashrath",
      "motherName": "Alka",
      "lastName": "Kalambe",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "श्वेताल",
      "lastNameMr": "कळंबे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_shwetal_alka_dhashrath_kalambe.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_shwetal_alka_dhashrath_kalambe.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SHIVANI_ALKA_DHASHRATH_KALAMBE",
      "firstName": "Shivani",
      "fatherName": "Dhashrath",
      "motherName": "Alka",
      "lastName": "Kalambe",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": "Kiku",
      "commonNameMr": null,
      "firstNameMr": "शिवानी",
      "lastNameMr": "कळंबे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_shivani_alka_dhashrath_kalambe.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_shivani_alka_dhashrath_kalambe.png",
      "tags": [],
      "private": false
    },
    {
      "id": "HARSHAL___KHONDE",
      "firstName": "Harshal",
      "fatherName": "",
      "motherName": "",
      "lastName": "Khonde",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "हर्षल",
      "lastNameMr": "खोंडे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_harshal___khonde.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_harshal___khonde.png",
      "tags": [],
      "private": false
    },
    {
      "id": "YASHMAK_TRUSHALI_SHWETAL_KALAMBE",
      "firstName": "Yashmak",
      "fatherName": "Shwetal",
      "motherName": "Trushali",
      "lastName": "Kalambe",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "यशमक",
      "lastNameMr": "कळंबे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_yashmak_trushali_shwetal_kalambe.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_yashmak_trushali_shwetal_kalambe.png",
      "tags": [],
      "private": false
    },
    {
      "id": "VIRIKA_SHIVANI_HARSHAL_KHONDE",
      "firstName": "Virika",
      "fatherName": "Harshal",
      "motherName": "Shivani",
      "lastName": "Khonde",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "विरिका",
      "lastNameMr": "खोंडे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_virika_shivani_harshal_khonde.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_virika_shivani_harshal_khonde.png",
      "tags": [],
      "private": false
    },
    {
      "id": "DAKSH_SHIVANI_HARSHAL_KHONDE",
      "firstName": "Daksh",
      "fatherName": "Harshal",
      "motherName": "Shivani",
      "lastName": "Khonde",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "दक्ष",
      "lastNameMr": "खोंडे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_daksh_shivani_harshal_khonde.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_daksh_shivani_harshal_khonde.png",
      "tags": [],
      "private": false
    },
    {
      "id": "AARTI_KALINDI_PRAKASHCHANDRA_BISNE",
      "firstName": "Aarti",
      "fatherName": "Prakashchandra",
      "motherName": "Kalindi",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": "Dolli",
      "commonNameMr": null,
      "firstNameMr": "आरती",
      "lastNameMr": "बिस्ने",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_aarti_kalindi_prakashchandra_bisne.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_aarti_kalindi_prakashchandra_bisne.png",
      "tags": [],
      "private": false
    },
    {
      "id": "AMIT_KALINDI_PRAKASHCHANDRA_BISNE",
      "firstName": "Amit",
      "fatherName": "Prakashchandra",
      "motherName": "Kalindi",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "अमित",
      "lastNameMr": "बिस्ने",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_amit_kalindi_prakashchandra_bisne.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_amit_kalindi_prakashchandra_bisne.png",
      "tags": [],
      "private": false
    },
    {
      "id": "VISHAL___PAHUNE",
      "firstName": "Vishal",
      "fatherName": "",
      "motherName": "",
      "lastName": "Pahune",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "विशाल",
      "lastNameMr": "पाहुणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_vishal___pahune.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_vishal___pahune.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SHRESHT_AARTI_VISHAL_PAHUNE",
      "firstName": "Shresht",
      "fatherName": "Vishal",
      "motherName": "Aarti",
      "lastName": "Pahune",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "श्रेष्ठ",
      "lastNameMr": "पाहुणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_shresht_aarti_vishal_pahune.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_shresht_aarti_vishal_pahune.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SHRIMEI_AARTI_VISHAL_PAHUNE",
      "firstName": "Shrimei",
      "fatherName": "Vishal",
      "motherName": "Aarti",
      "lastName": "Pahune",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "श्रीमी",
      "lastNameMr": "पाहुणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_shrimei_aarti_vishal_pahune.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_shrimei_aarti_vishal_pahune.png",
      "tags": [],
      "private": false
    },
    {
      "id": "ANANYA_MAITHALI_AMIT_BISNE",
      "firstName": "Ananya",
      "fatherName": "Amit",
      "motherName": "Maithali",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": "2007-07-02",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "अनन्या",
      "lastNameMr": "बिस्ने",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_ananya_maithali_amit_bisne.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_ananya_maithali_amit_bisne.png",
      "tags": [],
      "private": false
    },
    {
      "id": "VIVAN_MAITHALI_AMIT_BISNE",
      "firstName": "Vivan",
      "fatherName": "Amit",
      "motherName": "Maithali",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": "2010-12-18",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "विवान",
      "lastNameMr": "बिस्ने",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_vivan_maithali_amit_bisne.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_vivan_maithali_amit_bisne.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SUMEET_HEERA_VIJAY_WAGHMARE",
      "firstName": "Sumeet",
      "fatherName": "Vijay",
      "motherName": "Heera",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "सुमित",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_sumeet_heera_vijay_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_sumeet_heera_vijay_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SUSMIT_HEERA_VIJAY_WAGHMARE",
      "firstName": "Susmit",
      "fatherName": "Vijay",
      "motherName": "Heera",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "सुस्मित",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_susmit_heera_vijay_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_susmit_heera_vijay_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "RIYAN_MAYURI_SUSMIT_WAGHMARE",
      "firstName": "Riyan",
      "fatherName": "Susmit",
      "motherName": "Mayuri",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "रियान",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_riyan_mayuri_susmit_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_riyan_mayuri_susmit_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "firstName": "Saurabhi",
      "fatherName": "Ajay",
      "motherName": "Sangeeta",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "सौरभी",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_saurabhi_sangeeta_ajay_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_saurabhi_sangeeta_ajay_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "firstName": "Aishwarya",
      "fatherName": "Ajay",
      "motherName": "Sangeeta",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "ऐश्वर्या",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_aishwarya_sangeeta_ajay_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_aishwarya_sangeeta_ajay_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "VEDANT_SANGEETA_AJAY_WAGHMARE",
      "firstName": "Vedant",
      "fatherName": "Ajay",
      "motherName": "Sangeeta",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "वेदांत",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_vedant_sangeeta_ajay_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_vedant_sangeeta_ajay_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "GAURAV___BHIRUD",
      "firstName": "Gaurav",
      "fatherName": "",
      "motherName": "",
      "lastName": "Bhirud",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "गौरव",
      "lastNameMr": "भिरुड",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_gaurav___bhirud.jpg",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_gaurav___bhirud.jpg",
      "tags": [],
      "private": false
    },
    {
      "id": "SHASHWAT___BAVANKAR",
      "firstName": "Shashwat",
      "fatherName": "",
      "motherName": "",
      "lastName": "Bavankar",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "शाश्वत",
      "lastNameMr": "बावनकर",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_shashwat___bavankar.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_shashwat___bavankar.png",
      "tags": [],
      "private": false
    },
    {
      "id": "ARYAN_BHAVANA_SHASHI_WAGHMARE",
      "firstName": "Aryan",
      "fatherName": "Shashi",
      "motherName": "Bhavana",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "आर्यन",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_aryan_bhavana_shashi_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_aryan_bhavana_shashi_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "SHRIYA_BHAVANA_SHASHI_WAGHMARE",
      "firstName": "Shriya",
      "fatherName": "Shashi",
      "motherName": "Bhavana",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "single",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "श्रिया",
      "lastNameMr": "वाघमारे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_shriya_bhavana_shashi_waghmare.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_shriya_bhavana_shashi_waghmare.png",
      "tags": [],
      "private": false
    },
    {
      "id": "MAITHALI_RATNA_YOGESHWAR_BHARANPURE",
      "firstName": "Maithali",
      "fatherName": "Yogeshwar",
      "motherName": "Ratna",
      "lastName": "Bharanpure",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "मैथिली",
      "lastNameMr": "भरणपुरे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_maithali_ratna_yogeshwar_bharanpure.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_maithali_ratna_yogeshwar_bharanpure.png",
      "tags": [],
      "private": false
    },
    {
      "id": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "firstName": "Hitesh",
      "fatherName": "Shankar",
      "motherName": "Jyoti",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": "1985-12-29",
      "birthPlace": "Nagpur",
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": "हितेश",
      "lastNameMr": "साठवणे",
      "biography": null,
      "profilePhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/profile_hitesh_jyoti_shankar_sathawane.png",
      "backgroundPhoto": "https://pub-51dbdc7eb2f346efb74d0ec6e3b08829.r2.dev/background_hitesh_jyoti_shankar_sathawane.png",
      "tags": [],
      "private": false
    },
    {
      "id": "BHIMRAO___BIRADAR",
      "firstName": "Bhimrao",
      "fatherName": "",
      "motherName": "",
      "lastName": "Biradar",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Father of Swati Biradar.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "CHAYA___BIRADAR",
      "firstName": "Chaya",
      "fatherName": "",
      "motherName": "",
      "lastName": "Biradar",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Swati Biradar.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "VATSALA___SATHAWANE",
      "firstName": "Vatsala",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Shankar Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "BHASKARRAO___WAGHMARE",
      "firstName": "Bhaskarrao",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "M",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Father of Jyoti Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "MANAROMA___WAGHMARE",
      "firstName": "Manaroma",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Jyoti Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "VITTHALRAO___BISNE",
      "firstName": "Vitthalrao",
      "fatherName": "",
      "motherName": "",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "M",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Father of Prakashchandra Bisne.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "INDIRABAI___BISNE",
      "firstName": "Indirabai",
      "fatherName": "",
      "motherName": "",
      "lastName": "Bisne",
      "maidenName": null,
      "gender": "F",
      "status": "deceased",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Prakashchandra Bisne.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHAILA___SATHAWANE",
      "firstName": "Shaila",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Rahul Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SHRUTI___SATHAWANE",
      "firstName": "Shruti",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Takshita Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "MEENAKSHI___SATHAWANE",
      "firstName": "Meenakshi",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Saurabh Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "KALPANA___SATHAWANE",
      "firstName": "Kalpana",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Vatsal Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "TRUSHALI___KALAMBE",
      "firstName": "Trushali",
      "fatherName": "",
      "motherName": "",
      "lastName": "Kalambe",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Yashmak Kalambe.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "HEERA___WAGHMARE",
      "firstName": "Heera",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Sumeet Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "MAYURI___WAGHMARE",
      "firstName": "Mayuri",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Riyan Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "SANGEETA___WAGHMARE",
      "firstName": "Sangeeta",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Saurabhi Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "BHAVANA___WAGHMARE",
      "firstName": "Bhavana",
      "fatherName": "",
      "motherName": "",
      "lastName": "Waghmare",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Aryan Waghmare.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "YOGESHWAR___BHARANPURE",
      "firstName": "Yogeshwar",
      "fatherName": "",
      "motherName": "",
      "lastName": "Bharanpure",
      "maidenName": null,
      "gender": "M",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Father of Maithali Bharanpure.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "RATNA___BHARANPURE",
      "firstName": "Ratna",
      "fatherName": "",
      "motherName": "",
      "lastName": "Bharanpure",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Mother of Maithali Bharanpure.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    },
    {
      "id": "ASHWINI___SATHAWANE",
      "firstName": "Ashwini",
      "fatherName": "",
      "motherName": "",
      "lastName": "Sathawane",
      "maidenName": null,
      "gender": "F",
      "status": "living",
      "maritalStatus": "married",
      "birthDate": null,
      "birthPlace": null,
      "deathDate": null,
      "deathPlace": null,
      "occupation": null,
      "education": null,
      "location": null,
      "commonName": null,
      "commonNameMr": null,
      "firstNameMr": null,
      "lastNameMr": null,
      "biography": "Spouse of Mrunal Sathawane.",
      "profilePhoto": null,
      "tags": [],
      "private": false
    }
  ],
  "relationships": [
    {
      "id": "R_M_BHIMRAO___BIRADAR_CHAYA___BIRADAR",
      "type": "marriage",
      "person1Id": "BHIMRAO___BIRADAR",
      "person2Id": "CHAYA___BIRADAR",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_SAMPATHRAO___SATHAWANE_VATSALA___SATHAWANE",
      "type": "marriage",
      "person1Id": "SAMPATHRAO___SATHAWANE",
      "person2Id": "VATSALA___SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_BHASKARRAO___WAGHMARE_MANAROMA___WAGHMARE",
      "type": "marriage",
      "person1Id": "BHASKARRAO___WAGHMARE",
      "person2Id": "MANAROMA___WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_HITESH_JYOTI_SHANKAR_SATHAWANE_SWATI_CHAYA_BHIMRAO_BIRADAR",
      "type": "marriage",
      "person1Id": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "person2Id": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_INDIRABAI___BISNE_VITTHALRAO___BISNE",
      "type": "marriage",
      "person1Id": "INDIRABAI___BISNE",
      "person2Id": "VITTHALRAO___BISNE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_JYOTI_MANAROMA_BHASKARRAO_WAGHMARE_SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "marriage",
      "person1Id": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "person2Id": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_GAURAV_JYOTI_SHANKAR_SATHAWANE_RAJSHREE___LANJEWAR",
      "type": "marriage",
      "person1Id": "GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "person2Id": "RAJSHREE___LANJEWAR",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE_SHAILA___SATHAWANE",
      "type": "marriage",
      "person1Id": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "person2Id": "SHAILA___SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_RAHUL_SHAILA_MAHADEO_SATHAWANE_SHRUTI___SATHAWANE",
      "type": "marriage",
      "person1Id": "RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "person2Id": "SHRUTI___SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_MEENAKSHI___SATHAWANE_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "marriage",
      "person1Id": "MEENAKSHI___SATHAWANE",
      "person2Id": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_KALPANA___SATHAWANE_RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "marriage",
      "person1Id": "KALPANA___SATHAWANE",
      "person2Id": "RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_ALKA_VATSALA_SAMPATHRAO_SATHAWANE_DHASHRATH___KALAMBE",
      "type": "marriage",
      "person1Id": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "person2Id": "DHASHRATH___KALAMBE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_SHWETAL_ALKA_DHASHRATH_KALAMBE_TRUSHALI___KALAMBE",
      "type": "marriage",
      "person1Id": "SHWETAL_ALKA_DHASHRATH_KALAMBE",
      "person2Id": "TRUSHALI___KALAMBE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_HARSHAL___KHONDE_SHIVANI_ALKA_DHASHRATH_KALAMBE",
      "type": "marriage",
      "person1Id": "HARSHAL___KHONDE",
      "person2Id": "SHIVANI_ALKA_DHASHRATH_KALAMBE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_KALINDI_MANAROMA_BHASKARRAO_WAGHMARE_PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE",
      "type": "marriage",
      "person1Id": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "person2Id": "PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_AARTI_KALINDI_PRAKASHCHANDRA_BISNE_VISHAL___PAHUNE",
      "type": "marriage",
      "person1Id": "AARTI_KALINDI_PRAKASHCHANDRA_BISNE",
      "person2Id": "VISHAL___PAHUNE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_AMIT_KALINDI_PRAKASHCHANDRA_BISNE_MAITHALI_RATNA_YOGESHWAR_BHARANPURE",
      "type": "marriage",
      "person1Id": "AMIT_KALINDI_PRAKASHCHANDRA_BISNE",
      "person2Id": "MAITHALI_RATNA_YOGESHWAR_BHARANPURE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_HEERA___WAGHMARE_VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "marriage",
      "person1Id": "HEERA___WAGHMARE",
      "person2Id": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_MAYURI___WAGHMARE_SUSMIT_HEERA_VIJAY_WAGHMARE",
      "type": "marriage",
      "person1Id": "MAYURI___WAGHMARE",
      "person2Id": "SUSMIT_HEERA_VIJAY_WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_AJAY_MANAROMA_BHASKARRAO_WAGHMARE_SANGEETA___WAGHMARE",
      "type": "marriage",
      "person1Id": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "person2Id": "SANGEETA___WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_BHAVANA___WAGHMARE_SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "marriage",
      "person1Id": "BHAVANA___WAGHMARE",
      "person2Id": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_RATNA___BHARANPURE_YOGESHWAR___BHARANPURE",
      "type": "marriage",
      "person1Id": "RATNA___BHARANPURE",
      "person2Id": "YOGESHWAR___BHARANPURE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": "Auto-created parental marriage link."
    },
    {
      "id": "R_M_ASHWINI___SATHAWANE_MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "type": "marriage",
      "person1Id": "ASHWINI___SATHAWANE",
      "person2Id": "MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R_M_GAURAV___BHIRUD_SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "type": "marriage",
      "person1Id": "GAURAV___BHIRUD",
      "person2Id": "SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R_M_AISHWARYA_SANGEETA_AJAY_WAGHMARE_SHASHWAT___BAVANKAR",
      "type": "marriage",
      "person1Id": "AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "person2Id": "SHASHWAT___BAVANKAR",
      "startDate": null,
      "endDate": null,
      "endReason": null,
      "place": null,
      "notes": null
    },
    {
      "id": "R_PC_BHIMRAO___BIRADAR_SWATI_CHAYA_BHIMRAO_BIRADAR",
      "type": "parent-child",
      "parentId": "BHIMRAO___BIRADAR",
      "childId": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "relation": "biological"
    },
    {
      "id": "R_PC_CHAYA___BIRADAR_SWATI_CHAYA_BHIMRAO_BIRADAR",
      "type": "parent-child",
      "parentId": "CHAYA___BIRADAR",
      "childId": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "relation": "biological"
    },
    {
      "id": "R_PC_SAMPATHRAO___SATHAWANE_SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SAMPATHRAO___SATHAWANE",
      "childId": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VATSALA___SATHAWANE_SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "VATSALA___SATHAWANE",
      "childId": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HITESH_JYOTI_SHANKAR_SATHAWANE_DHRUV_SWATI_HITESH_SATHAWANE",
      "type": "parent-child",
      "parentId": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "childId": "DHRUV_SWATI_HITESH_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SWATI_CHAYA_BHIMRAO_BIRADAR_DHRUV_SWATI_HITESH_SATHAWANE",
      "type": "parent-child",
      "parentId": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "childId": "DHRUV_SWATI_HITESH_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HITESH_JYOTI_SHANKAR_SATHAWANE_ARJUN_SWATI_HITESH_SATHAWANE",
      "type": "parent-child",
      "parentId": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "childId": "ARJUN_SWATI_HITESH_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SWATI_CHAYA_BHIMRAO_BIRADAR_ARJUN_SWATI_HITESH_SATHAWANE",
      "type": "parent-child",
      "parentId": "SWATI_CHAYA_BHIMRAO_BIRADAR",
      "childId": "ARJUN_SWATI_HITESH_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SAMPATHRAO___SATHAWANE_MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SAMPATHRAO___SATHAWANE",
      "childId": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VATSALA___SATHAWANE_MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "VATSALA___SATHAWANE",
      "childId": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SAMPATHRAO___SATHAWANE_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SAMPATHRAO___SATHAWANE",
      "childId": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VATSALA___SATHAWANE_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "VATSALA___SATHAWANE",
      "childId": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SAMPATHRAO___SATHAWANE_RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SAMPATHRAO___SATHAWANE",
      "childId": "RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VATSALA___SATHAWANE_RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "VATSALA___SATHAWANE",
      "childId": "RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SAMPATHRAO___SATHAWANE_ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SAMPATHRAO___SATHAWANE",
      "childId": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VATSALA___SATHAWANE_ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "type": "parent-child",
      "parentId": "VATSALA___SATHAWANE",
      "childId": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHASKARRAO___WAGHMARE_SHIRIKANTH_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHASKARRAO___WAGHMARE",
      "childId": "SHIRIKANTH_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MANAROMA___WAGHMARE_SHIRIKANTH_MANAROMA_BHASKARRAO_WAGHMARE",
      "type": "parent-child",
      "parentId": "MANAROMA___WAGHMARE",
      "childId": "SHIRIKANTH_MANAROMA_BHASKARRAO_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VITTHALRAO___BISNE_PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE",
      "type": "parent-child",
      "parentId": "VITTHALRAO___BISNE",
      "childId": "PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_INDIRABAI___BISNE_PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE",
      "type": "parent-child",
      "parentId": "INDIRABAI___BISNE",
      "childId": "PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE_GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_JYOTI_MANAROMA_BHASKARRAO_WAGHMARE_GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_GAURAV_JYOTI_SHANKAR_SATHAWANE_ERISHA_RAJSHREE_GAURAV_SATHAWANE",
      "type": "parent-child",
      "parentId": "GAURAV_JYOTI_SHANKAR_SATHAWANE",
      "childId": "ERISHA_RAJSHREE_GAURAV_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_RAJSHREE___LANJEWAR_ERISHA_RAJSHREE_GAURAV_SATHAWANE",
      "type": "parent-child",
      "parentId": "RAJSHREE___LANJEWAR",
      "childId": "ERISHA_RAJSHREE_GAURAV_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE_RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "type": "parent-child",
      "parentId": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHAILA___SATHAWANE_RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SHAILA___SATHAWANE",
      "childId": "RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE_MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "type": "parent-child",
      "parentId": "MAHADEO_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHAILA___SATHAWANE_MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "type": "parent-child",
      "parentId": "SHAILA___SATHAWANE",
      "childId": "MRUNAL_SHAILA_MAHADEO_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_RAHUL_SHAILA_MAHADEO_SATHAWANE_TAKSHITA_SHRUTI_RAHUL_SATHAWANE",
      "type": "parent-child",
      "parentId": "RAHUL_SHAILA_MAHADEO_SATHAWANE",
      "childId": "TAKSHITA_SHRUTI_RAHUL_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHRUTI___SATHAWANE_TAKSHITA_SHRUTI_RAHUL_SATHAWANE",
      "type": "parent-child",
      "parentId": "SHRUTI___SATHAWANE",
      "childId": "TAKSHITA_SHRUTI_RAHUL_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE_SAURABH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "SAURABH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MEENAKSHI___SATHAWANE_SAURABH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "MEENAKSHI___SATHAWANE",
      "childId": "SAURABH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE_SIDDHARTH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "SIDDHARTH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MEENAKSHI___SATHAWANE_SIDDHARTH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "MEENAKSHI___SATHAWANE",
      "childId": "SIDDHARTH_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE_SAMEER_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "SUDHAKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "SAMEER_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MEENAKSHI___SATHAWANE_SAMEER_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "MEENAKSHI___SATHAWANE",
      "childId": "SAMEER_MEENAKSHI_SUDHAKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE_VATSAL_KALPANA_RATNAKR_SATHAWANE",
      "type": "parent-child",
      "parentId": "RATNAKR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "VATSAL_KALPANA_RATNAKR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_KALPANA___SATHAWANE_VATSAL_KALPANA_RATNAKR_SATHAWANE",
      "type": "parent-child",
      "parentId": "KALPANA___SATHAWANE",
      "childId": "VATSAL_KALPANA_RATNAKR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_DHASHRATH___KALAMBE_SHWETAL_ALKA_DHASHRATH_KALAMBE",
      "type": "parent-child",
      "parentId": "DHASHRATH___KALAMBE",
      "childId": "SHWETAL_ALKA_DHASHRATH_KALAMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_ALKA_VATSALA_SAMPATHRAO_SATHAWANE_SHWETAL_ALKA_DHASHRATH_KALAMBE",
      "type": "parent-child",
      "parentId": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "SHWETAL_ALKA_DHASHRATH_KALAMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_DHASHRATH___KALAMBE_SHIVANI_ALKA_DHASHRATH_KALAMBE",
      "type": "parent-child",
      "parentId": "DHASHRATH___KALAMBE",
      "childId": "SHIVANI_ALKA_DHASHRATH_KALAMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_ALKA_VATSALA_SAMPATHRAO_SATHAWANE_SHIVANI_ALKA_DHASHRATH_KALAMBE",
      "type": "parent-child",
      "parentId": "ALKA_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "SHIVANI_ALKA_DHASHRATH_KALAMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHWETAL_ALKA_DHASHRATH_KALAMBE_YASHMAK_TRUSHALI_SHWETAL_KALAMBE",
      "type": "parent-child",
      "parentId": "SHWETAL_ALKA_DHASHRATH_KALAMBE",
      "childId": "YASHMAK_TRUSHALI_SHWETAL_KALAMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_TRUSHALI___KALAMBE_YASHMAK_TRUSHALI_SHWETAL_KALAMBE",
      "type": "parent-child",
      "parentId": "TRUSHALI___KALAMBE",
      "childId": "YASHMAK_TRUSHALI_SHWETAL_KALAMBE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HARSHAL___KHONDE_VIRIKA_SHIVANI_HARSHAL_KHONDE",
      "type": "parent-child",
      "parentId": "HARSHAL___KHONDE",
      "childId": "VIRIKA_SHIVANI_HARSHAL_KHONDE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHIVANI_ALKA_DHASHRATH_KALAMBE_VIRIKA_SHIVANI_HARSHAL_KHONDE",
      "type": "parent-child",
      "parentId": "SHIVANI_ALKA_DHASHRATH_KALAMBE",
      "childId": "VIRIKA_SHIVANI_HARSHAL_KHONDE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HARSHAL___KHONDE_DAKSH_SHIVANI_HARSHAL_KHONDE",
      "type": "parent-child",
      "parentId": "HARSHAL___KHONDE",
      "childId": "DAKSH_SHIVANI_HARSHAL_KHONDE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHIVANI_ALKA_DHASHRATH_KALAMBE_DAKSH_SHIVANI_HARSHAL_KHONDE",
      "type": "parent-child",
      "parentId": "SHIVANI_ALKA_DHASHRATH_KALAMBE",
      "childId": "DAKSH_SHIVANI_HARSHAL_KHONDE",
      "relation": "biological"
    },
    {
      "id": "R_PC_PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE_AARTI_KALINDI_PRAKASHCHANDRA_BISNE",
      "type": "parent-child",
      "parentId": "PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE",
      "childId": "AARTI_KALINDI_PRAKASHCHANDRA_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_KALINDI_MANAROMA_BHASKARRAO_WAGHMARE_AARTI_KALINDI_PRAKASHCHANDRA_BISNE",
      "type": "parent-child",
      "parentId": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "AARTI_KALINDI_PRAKASHCHANDRA_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE_AMIT_KALINDI_PRAKASHCHANDRA_BISNE",
      "type": "parent-child",
      "parentId": "PRAKASHCHANDRA_INDIRABAI_VITTHALRAO_BISNE",
      "childId": "AMIT_KALINDI_PRAKASHCHANDRA_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_KALINDI_MANAROMA_BHASKARRAO_WAGHMARE_AMIT_KALINDI_PRAKASHCHANDRA_BISNE",
      "type": "parent-child",
      "parentId": "KALINDI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "AMIT_KALINDI_PRAKASHCHANDRA_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VISHAL___PAHUNE_SHRESHT_AARTI_VISHAL_PAHUNE",
      "type": "parent-child",
      "parentId": "VISHAL___PAHUNE",
      "childId": "SHRESHT_AARTI_VISHAL_PAHUNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AARTI_KALINDI_PRAKASHCHANDRA_BISNE_SHRESHT_AARTI_VISHAL_PAHUNE",
      "type": "parent-child",
      "parentId": "AARTI_KALINDI_PRAKASHCHANDRA_BISNE",
      "childId": "SHRESHT_AARTI_VISHAL_PAHUNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VISHAL___PAHUNE_SHRIMEI_AARTI_VISHAL_PAHUNE",
      "type": "parent-child",
      "parentId": "VISHAL___PAHUNE",
      "childId": "SHRIMEI_AARTI_VISHAL_PAHUNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AARTI_KALINDI_PRAKASHCHANDRA_BISNE_SHRIMEI_AARTI_VISHAL_PAHUNE",
      "type": "parent-child",
      "parentId": "AARTI_KALINDI_PRAKASHCHANDRA_BISNE",
      "childId": "SHRIMEI_AARTI_VISHAL_PAHUNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AMIT_KALINDI_PRAKASHCHANDRA_BISNE_ANANYA_MAITHALI_AMIT_BISNE",
      "type": "parent-child",
      "parentId": "AMIT_KALINDI_PRAKASHCHANDRA_BISNE",
      "childId": "ANANYA_MAITHALI_AMIT_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MAITHALI_RATNA_YOGESHWAR_BHARANPURE_ANANYA_MAITHALI_AMIT_BISNE",
      "type": "parent-child",
      "parentId": "MAITHALI_RATNA_YOGESHWAR_BHARANPURE",
      "childId": "ANANYA_MAITHALI_AMIT_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AMIT_KALINDI_PRAKASHCHANDRA_BISNE_VIVAN_MAITHALI_AMIT_BISNE",
      "type": "parent-child",
      "parentId": "AMIT_KALINDI_PRAKASHCHANDRA_BISNE",
      "childId": "VIVAN_MAITHALI_AMIT_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MAITHALI_RATNA_YOGESHWAR_BHARANPURE_VIVAN_MAITHALI_AMIT_BISNE",
      "type": "parent-child",
      "parentId": "MAITHALI_RATNA_YOGESHWAR_BHARANPURE",
      "childId": "VIVAN_MAITHALI_AMIT_BISNE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VIJAY_MANAROMA_BHASKARRAO_WAGHMARE_SUMEET_HEERA_VIJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "SUMEET_HEERA_VIJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HEERA___WAGHMARE_SUMEET_HEERA_VIJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "HEERA___WAGHMARE",
      "childId": "SUMEET_HEERA_VIJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_VIJAY_MANAROMA_BHASKARRAO_WAGHMARE_SUSMIT_HEERA_VIJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "VIJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "SUSMIT_HEERA_VIJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_HEERA___WAGHMARE_SUSMIT_HEERA_VIJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "HEERA___WAGHMARE",
      "childId": "SUSMIT_HEERA_VIJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SUSMIT_HEERA_VIJAY_WAGHMARE_RIYAN_MAYURI_SUSMIT_WAGHMARE",
      "type": "parent-child",
      "parentId": "SUSMIT_HEERA_VIJAY_WAGHMARE",
      "childId": "RIYAN_MAYURI_SUSMIT_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_MAYURI___WAGHMARE_RIYAN_MAYURI_SUSMIT_WAGHMARE",
      "type": "parent-child",
      "parentId": "MAYURI___WAGHMARE",
      "childId": "RIYAN_MAYURI_SUSMIT_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AJAY_MANAROMA_BHASKARRAO_WAGHMARE_SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SANGEETA___WAGHMARE_SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "SANGEETA___WAGHMARE",
      "childId": "SAURABHI_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AJAY_MANAROMA_BHASKARRAO_WAGHMARE_AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SANGEETA___WAGHMARE_AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "SANGEETA___WAGHMARE",
      "childId": "AISHWARYA_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_AJAY_MANAROMA_BHASKARRAO_WAGHMARE_VEDANT_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "AJAY_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "VEDANT_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SANGEETA___WAGHMARE_VEDANT_SANGEETA_AJAY_WAGHMARE",
      "type": "parent-child",
      "parentId": "SANGEETA___WAGHMARE",
      "childId": "VEDANT_SANGEETA_AJAY_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHASHI_MANAROMA_BHASKARRAO_WAGHMARE_ARYAN_BHAVANA_SHASHI_WAGHMARE",
      "type": "parent-child",
      "parentId": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "ARYAN_BHAVANA_SHASHI_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHAVANA___WAGHMARE_ARYAN_BHAVANA_SHASHI_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHAVANA___WAGHMARE",
      "childId": "ARYAN_BHAVANA_SHASHI_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHASHI_MANAROMA_BHASKARRAO_WAGHMARE_SHRIYA_BHAVANA_SHASHI_WAGHMARE",
      "type": "parent-child",
      "parentId": "SHASHI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "SHRIYA_BHAVANA_SHASHI_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_BHAVANA___WAGHMARE_SHRIYA_BHAVANA_SHASHI_WAGHMARE",
      "type": "parent-child",
      "parentId": "BHAVANA___WAGHMARE",
      "childId": "SHRIYA_BHAVANA_SHASHI_WAGHMARE",
      "relation": "biological"
    },
    {
      "id": "R_PC_YOGESHWAR___BHARANPURE_MAITHALI_RATNA_YOGESHWAR_BHARANPURE",
      "type": "parent-child",
      "parentId": "YOGESHWAR___BHARANPURE",
      "childId": "MAITHALI_RATNA_YOGESHWAR_BHARANPURE",
      "relation": "biological"
    },
    {
      "id": "R_PC_RATNA___BHARANPURE_MAITHALI_RATNA_YOGESHWAR_BHARANPURE",
      "type": "parent-child",
      "parentId": "RATNA___BHARANPURE",
      "childId": "MAITHALI_RATNA_YOGESHWAR_BHARANPURE",
      "relation": "biological"
    },
    {
      "id": "R_PC_SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE_HITESH_JYOTI_SHANKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "SHANKAR_VATSALA_SAMPATHRAO_SATHAWANE",
      "childId": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "relation": "biological"
    },
    {
      "id": "R_PC_JYOTI_MANAROMA_BHASKARRAO_WAGHMARE_HITESH_JYOTI_SHANKAR_SATHAWANE",
      "type": "parent-child",
      "parentId": "JYOTI_MANAROMA_BHASKARRAO_WAGHMARE",
      "childId": "HITESH_JYOTI_SHANKAR_SATHAWANE",
      "relation": "biological"
    }
  ],
  "events": [],
  "media": [],
  "scrapbook": {}
};
